# Ruby のベースイメージを指定
FROM ruby:3.4.9

# 環境変数の設定
ENV LANG C.UTF-8  # 日本語対応
ENV TZ Asia/Tokyo # タイムゾーンを日本に設定

# Node.js と yarn のセットアップ 2026-06-21更新
# 1. 基本パッケージのインストール
# 2. Node.js v24 のセットアップスクリプト実行
# 3. yarn のリポジトリ設定
RUN apt-get update -qq \
  && apt-get install -y ca-certificates curl gnupg \
  && mkdir -p /etc/apt/keyrings \
  && curl -fsSL https://deb.nodesource.com/setup_24.x | bash - \
  && apt-get install -y nodejs \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/yarn-archive-keyring.gpg \
  && echo "deb [signed-by=/usr/share/keyrings/yarn-archive-keyring.gpg] https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && apt-get update -qq \
  && apt-get install -y yarn

# Node.js、yarn、その他の必要なパッケージをインストール
#  + apt-get updateで作成されるパッケージリストのキャッシュを削除し、Dockerイメージのサイズを削減
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn vim libvips libvips-dev postgresql-client \
&& rm -rf /var/lib/apt/lists/*


# アプリケーションディレクトリの作成
RUN mkdir /myapp
WORKDIR /myapp

# Bundlerのインストール
RUN gem install bundler

# アプリケーションのコードをコピー
COPY . /myapp

# Gemfileのコピー… gemのバージョンを固定する = チームメンバー間でバージョンを統一するため。Gemfile.lockがないと、bundle install時に最新版がインストールされる可能性あり。
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemapp/Gemfile.lock
RUN bundle install

CMD ["bin/dev"]